apiVersion: v1
kind: Service
metadata:
  name: api-alpha
spec:
  type: NodePort
  ports:
    - port: 8888
      name: http
  selector:
    app: api
    version: alpha
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpha
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
      version: alpha
  template:
    metadata:
      labels:
        app: api
        version: alpha
    spec:
      containers:
      - name: flask-api
        imagePullPolicy: Always
        image: alavarello/test-api:alpha
        ports:
        - containerPort: 8888
