apiVersion: v1
kind: Service
metadata:
  name: api-beta
spec:
  type: ClusterIP
  ports:
    - port: 8888
      name: http
  selector:
    app: api
    version: beta
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: beta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
      version: beta
  template:
    metadata:
      labels:
        app: api
        version: beta
    spec:
      containers:
      - name: flask-api
        imagePullPolicy: Always
        image: alavarello/test-api:beta
        ports:
        - containerPort: 8888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpha
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
      version: alpha
  template:
    metadata:
      labels:
        app: api
        version: alpha
    spec:
      containers:
      - name: flask-api
        imagePullPolicy: Always
        image: alavarello/test-api:alpha
        ports:
        - containerPort: 8888
