apiVersion: apps/v1
kind: Deployment
metadata:
  name: beta
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
      version: beta
  template:
    metadata:
      labels:
        app: api
        version: beta
    spec:
      containers:
      - name: flask-api
        imagePullPolicy: Always
        image: alavarello/test-api:beta
        ports:
        - containerPort: 8888
        env:
          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: database
                key: user
          - name: DATABASE_PASS
            valueFrom:
              secretKeyRef:
                name: database
                key: pass
          - name: DATABASE_NAME
            valueFrom:
              secretKeyRef:
                name: database
                key: name
