apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
   events {
      worker_connections  10240;
    }

    http {

      server {
          listen       80;
          server_name  _;
          location /v1/ {
              proxy_pass http://api-alpha:8888/;
          }

          location /v2/ {
              proxy_pass http://api-beta:8888/;
          }
      }
    }
