apiVersion: v1
kind: Service
metadata:
  name: http-service
spec:
  type: NodePort
  ports:
    - port: 8888
      nodePort: 32333
  selector:
    app: app-http
---
apiVersion: v1
kind: Service
metadata:
  name: database-service
spec:
  type: ExternalName
  externalName: database
